// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4yIkTPcv9NhnnmMhICEeXcpvgtLxWQZI',
    appId: '1:859221902934:web:474e9d900d739b72115df7',
    messagingSenderId: '859221902934',
    projectId: 'friendlyapp-eefc6',
    authDomain: 'friendlyapp-eefc6.firebaseapp.com',
    storageBucket: 'friendlyapp-eefc6.appspot.com',
    measurementId: 'G-28CJLPJZVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjsurn3pvrS7PqUJQrlqL1mo0X2fJNh_c',
    appId: '1:859221902934:android:77114af41e11b72c115df7',
    messagingSenderId: '859221902934',
    projectId: 'friendlyapp-eefc6',
    storageBucket: 'friendlyapp-eefc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEGoB8t1ALst8mNykXAc0MmvZxW2g_jCQ',
    appId: '1:859221902934:ios:7f551777c285c994115df7',
    messagingSenderId: '859221902934',
    projectId: 'friendlyapp-eefc6',
    storageBucket: 'friendlyapp-eefc6.appspot.com',
    iosBundleId: 'com.example.friendlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEGoB8t1ALst8mNykXAc0MmvZxW2g_jCQ',
    appId: '1:859221902934:ios:43a70a4d63adec54115df7',
    messagingSenderId: '859221902934',
    projectId: 'friendlyapp-eefc6',
    storageBucket: 'friendlyapp-eefc6.appspot.com',
    iosBundleId: 'com.example.friendlyApp.RunnerTests',
  );
}
